source-optional=./binds.conf
source-optional=./execs.conf
source-optional=./monitors.conf
source-optional=./rules.conf
source-optional=./devices.conf

blur=0
shadows = 0

border_radius=0
focused_opacity=1.0
unfocused_opacity=1.0

animations=0
layer_animations=1
animation_type_open=slide
animation_type_close=slide
animation_fade_in=1
animation_fade_out=1
tag_animation_direction=0
zoom_initial_ratio=0.4
zoom_end_ratio=0.8
fadein_begin_opacity=0.5
fadeout_begin_opacity=0.8
animation_duration_move=500
animation_duration_open=400
animation_duration_tag=350
animation_duration_close=800
animation_duration_focus=0
animation_curve_open=0.46,1.0,0.29,1
animation_curve_move=0.46,1.0,0.29,1
animation_curve_tag=0.46,1.0,0.29,1
animation_curve_close=0.08,0.92,0,1
animation_curve_focus=0.46,1.0,0.29,1
animation_curve_opafadeout=0.5,0.5,0.5,0.5
animation_curve_opafadein=0.46,1.0,0.29,1

# Scroller Layout Setting
scroller_structs=20
scroller_default_proportion=0.5
scroller_focus_center=0
scroller_prefer_center=0
edge_scroller_pointer_focus=1
scroller_default_proportion_single=1.0
scroller_proportion_preset=0.5,0.8,1.0

# Master-Stack Layout Setting
new_is_master=1
default_mfact=0.55
default_nmaster=1
smartgaps=0

# Overview Setting
enable_hotarea=0

# Misc
no_border_when_single=0
axis_bind_apply_timeout=100
focus_on_activate=0
idleinhibit_ignore_visible=0
sloppyfocus=1
warpcursor=1
focus_cross_monitor=0
focus_cross_tag=0
enable_floating_snap=0
snap_distance=30
drag_tile_to_tile=1


# Appearance
# gappih=5
# gappiv=5
# gappoh=10
# gappov=10

gappih=2
gappiv=2
gappoh=4
gappov=4

scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=4 #4
rootcolor=0x282828ff
bordercolor=0x504945ff
focuscolor=0xd79921ff
maximizescreencolor=0xb8bb26ff
urgentcolor=0xcc241dff
scratchpadcolor=0x458588ff
globalcolor=0xb16286ff
overlaycolor=0x689d6aff

env=XDG_CURRENT_DESKTOP,Mango
env=XDG_SESSION_TYPE,wayland

